version: "3.9"
services:
  db:
    image: postgres:14.1
    environment:
      - POSTGRES_DB=development_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    ports:
      - "8432:5432"
volumes:
  postgres-data:
    external: false
